# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/
exec-once = nvidia-settings -a "[gpu:0]/GPUPowerMizerMode=1"
exec-once = sudo cpupower frequency-set -g performance
# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Escape Simulator — immediate rendering reduces input lag on Wayland
windowrule {
  name = escape-simulator-perf
  match:class = ^steam_app_1435790$
  immediate = on
  no_anim = on
}

# get songkey rs
windowrule {
  name = getsongkey-float
  match:class = ^getsongkey$
  float = 1
  center = 1
  size = 900 560
}

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu

env = WLR_NO_HARDWARE_CURSORS,1

# FL Studio - fix resize, fullscreen, and rendering issues on XWayland
windowrule {
  name = fl-studio-fix
  match:class = fl64.exe
  no_anim = on
  match:title = ^$
  no_focus = on
  no_blur = on
  no_max_size = on
  match:xwayland = true
  # suppress_event = fullscreen maximize
}

# Prevent stray empty XWayland floating windows (common Wine ghost windows) from stealing focus
#windowrule {
#  name = xwayland-nofocus
#  match:class = ^$
#  match:xwayland = true
#  no_focus = on
#}

# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf
