# ------------------ video ------------------ #
vo=gpu-next

profile=high-quality # https://github.com/mpv-player/mpv/blob/master/etc/builtin.conf#L54
hwdec=auto-copy-safe

target-colorspace-hint=yes

# ------------------ audio ------------------ #
# audio-file-auto=fuzzy # load audio files if the name almost matches
volume-max=300
audio-pitch-correction=yes # pitch audio when timescaling

# ------------------ mpv ------------------ #
# window sizing/placement
autofit-larger=92%x98%
geometry=50%:50%

# behaviour
keep-open=always
reset-on-next-file=pause

cursor-autohide-fs-only=yes # always show cursor in windowed
cursor-autohide=300

hr-seek=yes # precise seeking (not just keyframes)

# input-default-bindings=no

# slow down repeat rate when holding left/right arrows
input-ar-delay=500
input-ar-rate=10

script-opts='osc-title=${filename}'

# ------------------ interface ------------------ #
osc=no      # using custom osd
osd-bar=no  # disable volume bar
osd-level=1 # https://mpv.io/manual/master/#options-osd-level
osd-duration=1000

# ui
osd-font='URW Gothic'
osd-font-size=20
osd-color='#ffffff'
osd-border-color='#000000'
osd-border-size=1
osd-blur=0.2

# subtitles
blend-subtitles=no
sub-font="URW Gothic"
sub-ass-override=yes
sub-font-size=30
sub-pos=90
sub-outline-size=1
sub-shadow-offset=1
sub-shadow-color="#000000"

# ------------------ subtitles ------------------ #
sub-auto=fuzzy # https://mpv.io/manual/master/#options-no-sub-auto

# ------------------ screenshots ------------------ #
screenshot-jpeg-quality=100      # mosquito noise
screenshot-jpeg-source-chroma=no # 420 -> 444 bug
screenshot-high-bit-depth=no     # 8@10 -> 16 bug
screenshot-directory="~/Pictures/mpv-screenshots"
screenshot-template="%f_%wH.%wM.%wS.%wT"

# ------------------ filetypes ------------------ #
[extension.webm]
loop-file=inf

[extension.flac]
autofit-larger=50%x50%
geometry=50%:50%
